config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch 'users/:id', to: 'users#update', as: 'update_user'
  delete 'destroy', to: 'users#destroy'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :dogs, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  has_many :dogs

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  helper_method :current_user

  private

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show]

  def new
    @dog = current_user.dogs.build
  end

  def create
    @dog = current_user.dogs.build(dog_params)
    if @dog.save
      flash[:success] = "Dog created successfully!"
      redirect_to dog_path(@dog)
    else
      flash.now[:error] = "Error creating dog. Please check the form and try again"
      render :new
    end
  end

  # GET /dogs
  def index
    @dogs = Dog.all
  end

  # GET /dogs/:id
  def show
  end

  private

  # Use a callback to share the common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :bio, :image, :image_url, :excitement, :energy, :laziness, :fun)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # makes sure the filds in the form are blank for a new user
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User created successfully!'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:format])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>
  <div>
    <%= form.label :image, 'Upload Image' %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :excitement %>
    <%= form.number_field :excitement %>
  </div>
  <div>
    <%= form.label :energy %>
    <%= form.number_field :energy %>
  </div>
  <div>
    <%= form.label :laziness %>
    <%= form.number_field :laziness %>
  </div>
  <div>
    <%= form.label :fun %>
    <%= form.number_field :fun %>
  </div>
  <div>
    <%= form.submit dog.new_record? ? 'Create Dog' : 'Update Dog' %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<%= render 'form', dog: @dog %>

app/views/dogs/index.html.erb
<h1>All Dogs</h1>
<%= link_to 'Add Dog', new_dog_path %>
<ul>
  <% @dogs.each do |dog| %>
    <li>
      <%= link_to dog.name, dog_path(dog) %>
    </li>
  <% end %>
</ul>

app/views/dogs/new.html.erb
<%= render 'form', dog: @dog %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<% if @dog.image.attached? %>
  <%= image_tag url_for(@dog.image), alt: @dog.name, size: "100x100", id: "dog_image" %>
<% else %>
  <p>No image available</p>
<% end %>
<h2>Stats</h2>
<ul>
  <li>Excitement: <%= @dog.excitement %></li>
  <li>Energy: <%= @dog.energy %></li>
  <li>Laziness: <%= @dog.laziness %></li>
  <li>Fun: <%= @dog.fun %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DOGBNB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container">
      <%# <main class="flex flex-col justify-center items-center w-screen	h-screen"> %>
      <%= yield %>
      <%# </main> %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<%= render 'shared/nav' %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'My Dogs', dogs_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'View Profile', user_path(current_user.id), class:"dropdown-item"%></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user.id), class:"dropdown-item"%></li>
              <li><%= link_to "Log out", logout_path, data: { turbo_action: 'action', turbo_method: :delete }, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', signup_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div>
  <div>
    <h1 class="text-blue-800 mb-10">Edit profile</h1>
    <%= form_with(model: @user, url: update_user_path, method: :patch) do |f| %>
      <%= f.label :firstname %>
      <%= f.text_field :firstname %>
      <%= f.label :lastname %>
      <%= f.text_field :lastname%>
      <%= f.label :email %>
      <%= f.email_field :email%>
      <%= f.label :password %>
      <%= f.password_field :password%>
      <%= f.submit "Update", class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being updated:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="">
  <h1 class="font-bold text-3xl text-blue-700">Create user page</h1>
  <%= form_with(model: @user, html: {class:"flex flex-col"}) do |f| %>
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Submit", class:"bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow"%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="justify-center items-center">
  <h1 class="font-bold text-black">User Profile Page</h1>
  <p class="text-gray-900 leading-none"><%=@user.firstname.capitalize()%> <%= @user.lastname.capitalize()%></p>
  <p class="text-gray-900 leading-none"><%=@user.email%></p>
  <p class="text-gray-600">Account created at: <%= @user.created_at %></p>
  <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow"><%= link_to 'Home', root_path%></button>
  <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow"><%= link_to "Edit", edit_user_path(@user)%></button>
  <%= button_to "Log out", logout_path, method: :delete, class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
  <%= button_to "Delete User", destroy_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
</div>